import type { Job, Line, QCEntry } from "./types";
import { uid } from "./utils-domain";

export const SEED_LINES: Line[] = [
  { id: "L1", name: "Line 1 — High Volume", capacityBph: 4800 },
  { id: "L2", name: "Line 2 — Standard", capacityBph: 3200 },
  { id: "L3", name: "Line 3 — Small Batch", capacityBph: 1500 },
];

const CUSTOMER_COLORS = ["#0ea5e9", "#22c55e", "#f97316", "#a855f7", "#ec4899", "#14b8a6"];

function isoDaysFromNow(days: number, hour = 8) {
  const d = new Date();
  d.setDate(d.getDate() + days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export function buildSeedJobs(): Job[] {
  return [
    {
      id: uid(),
      customer: "AquaPure Industries",
      product: "Industrial Surface Cleaner",
      sku: "KS-SC-500",
      bottleSize: "500ml",
      quantity: 24000,
      pallets: 20,
      dueDate: isoDaysFromNow(3),
      priority: "High",
      line: "L1",
      operator: "M. Hassan",
      bottlesPerHour: 4500,
      setupMinutes: 45,
      notes: "Customer requires lot photos.",
      rawMaterial: "Ready",
      labels: "Ready",
      packaging: "Ready",
      status: "Filling",
      scheduledStart: isoDaysFromNow(0, 7),
      bottlesCompleted: 9200,
      palletsCompleted: 7,
      downtimeMinutes: 18,
      actualRuntimeMinutes: 130,
      customerColor: CUSTOMER_COLORS[0],
      createdAt: new Date().toISOString(),
    },
    {
      id: uid(),
      customer: "GreenLeaf Agro",
      product: "Crop Defender Concentrate",
      sku: "KS-CD-1L",
      bottleSize: "1L",
      quantity: 12000,
      pallets: 12,
      dueDate: isoDaysFromNow(5),
      priority: "Urgent",
      line: "L2",
      operator: "P. Singh",
      bottlesPerHour: 3000,
      setupMinutes: 60,
      notes: "Hazmat labelling — double-check batch.",
      rawMaterial: "Ready",
      labels: "Pending",
      packaging: "Ready",
      status: "Setup",
      scheduledStart: isoDaysFromNow(0, 13),
      bottlesCompleted: 0,
      palletsCompleted: 0,
      downtimeMinutes: 0,
      actualRuntimeMinutes: 0,
      customerColor: CUSTOMER_COLORS[1],
      createdAt: new Date().toISOString(),
    },
    {
      id: uid(),
      customer: "MarinaCare",
      product: "Hull Treatment Spray",
      sku: "KS-HT-250",
      bottleSize: "250ml",
      quantity: 6000,
      pallets: 5,
      dueDate: isoDaysFromNow(1),
      priority: "Urgent",
      line: "L3",
      operator: "J. Okafor",
      bottlesPerHour: 1400,
      setupMinutes: 30,
      notes: "",
      rawMaterial: "Ready",
      labels: "Ready",
      packaging: "Ready",
      status: "QC Review",
      scheduledStart: isoDaysFromNow(0, 6),
      bottlesCompleted: 6000,
      palletsCompleted: 5,
      downtimeMinutes: 12,
      actualRuntimeMinutes: 280,
      customerColor: CUSTOMER_COLORS[2],
      createdAt: new Date().toISOString(),
    },
    {
      id: uid(),
      customer: "NovaChem",
      product: "Lab Solvent Mix",
      sku: "KS-LS-2L",
      bottleSize: "2L",
      quantity: 8000,
      pallets: 10,
      dueDate: isoDaysFromNow(7),
      priority: "Normal",
      line: "L2",
      operator: "Unassigned",
      bottlesPerHour: 2400,
      setupMinutes: 50,
      notes: "Schedule after GreenLeaf finishes.",
      rawMaterial: "Pending",
      labels: "Ready",
      packaging: "Pending",
      status: "Scheduled",
      scheduledStart: isoDaysFromNow(2, 8),
      bottlesCompleted: 0,
      palletsCompleted: 0,
      downtimeMinutes: 0,
      actualRuntimeMinutes: 0,
      customerColor: CUSTOMER_COLORS[3],
      createdAt: new Date().toISOString(),
    },
    {
      id: uid(),
      customer: "AquaPure Industries",
      product: "Floor Degreaser",
      sku: "KS-FD-1L",
      bottleSize: "1L",
      quantity: 15000,
      pallets: 14,
      dueDate: isoDaysFromNow(-1),
      priority: "High",
      line: "L1",
      operator: "M. Hassan",
      bottlesPerHour: 4200,
      setupMinutes: 40,
      notes: "Delayed due to capper jam.",
      rawMaterial: "Ready",
      labels: "Ready",
      packaging: "Ready",
      status: "Delayed",
      scheduledStart: isoDaysFromNow(-1, 6),
      bottlesCompleted: 9800,
      palletsCompleted: 9,
      downtimeMinutes: 75,
      actualRuntimeMinutes: 240,
      customerColor: CUSTOMER_COLORS[0],
      createdAt: new Date().toISOString(),
    },
    {
      id: uid(),
      customer: "PureHome Brands",
      product: "Glass Cleaner",
      sku: "KS-GC-500",
      bottleSize: "500ml",
      quantity: 18000,
      pallets: 15,
      dueDate: isoDaysFromNow(-3),
      priority: "Normal",
      line: "L1",
      operator: "S. Lewis",
      bottlesPerHour: 4600,
      setupMinutes: 35,
      notes: "",
      rawMaterial: "Ready",
      labels: "Ready",
      packaging: "Ready",
      status: "Complete",
      scheduledStart: isoDaysFromNow(-4, 7),
      bottlesCompleted: 18000,
      palletsCompleted: 15,
      downtimeMinutes: 22,
      actualRuntimeMinutes: 245,
      customerColor: CUSTOMER_COLORS[4],
      createdAt: new Date().toISOString(),
    },
  ];
}

export function buildSeedQC(jobs: Job[]): QCEntry[] {
  const out: QCEntry[] = [];
  const active = jobs.find((j) => j.status === "Filling");
  if (active) {
    for (let i = 1; i <= active.palletsCompleted; i++) {
      out.push({
        id: uid(),
        jobId: active.id,
        palletNumber: i,
        fillLevel: "Pass",
        capTightness: "Pass",
        labelAlignment: "Pass",
        batchCode: "Pass",
        leakCheck: "Pass",
        bottleCondition: "Pass",
        bottleCount: 1200,
        operatorName: active.operator,
        supervisorSignoff: "K. Brown",
        notes: "",
        timestamp: new Date(Date.now() - (active.palletsCompleted - i) * 45 * 60_000).toISOString(),
        result: "Pass",
      });
    }
  }
  return out;
}
