/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnleashedSyncRouteImport } from './routes/unleashed-sync'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as QcRouteImport } from './routes/qc'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LineSetupRouteImport } from './routes/line-setup'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CustomerSpecsRouteImport } from './routes/customer-specs'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksSyncFillReadyRouteImport } from './routes/api/public/hooks/sync-fill-ready'

const UnleashedSyncRoute = UnleashedSyncRouteImport.update({
  id: '/unleashed-sync',
  path: '/unleashed-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const QcRoute = QcRouteImport.update({
  id: '/qc',
  path: '/qc',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LineSetupRoute = LineSetupRouteImport.update({
  id: '/line-setup',
  path: '/line-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSpecsRoute = CustomerSpecsRouteImport.update({
  id: '/customer-specs',
  path: '/customer-specs',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncFillReadyRoute =
  ApiPublicHooksSyncFillReadyRouteImport.update({
    id: '/api/public/hooks/sync-fill-ready',
    path: '/api/public/hooks/sync-fill-ready',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/customer-specs': typeof CustomerSpecsRoute
  '/jobs': typeof JobsRoute
  '/line-setup': typeof LineSetupRoute
  '/live': typeof LiveRoute
  '/manufacturing': typeof ManufacturingRoute
  '/qc': typeof QcRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/unleashed-sync': typeof UnleashedSyncRoute
  '/api/public/hooks/sync-fill-ready': typeof ApiPublicHooksSyncFillReadyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/customer-specs': typeof CustomerSpecsRoute
  '/jobs': typeof JobsRoute
  '/line-setup': typeof LineSetupRoute
  '/live': typeof LiveRoute
  '/manufacturing': typeof ManufacturingRoute
  '/qc': typeof QcRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/unleashed-sync': typeof UnleashedSyncRoute
  '/api/public/hooks/sync-fill-ready': typeof ApiPublicHooksSyncFillReadyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/calendar': typeof CalendarRoute
  '/customer-specs': typeof CustomerSpecsRoute
  '/jobs': typeof JobsRoute
  '/line-setup': typeof LineSetupRoute
  '/live': typeof LiveRoute
  '/manufacturing': typeof ManufacturingRoute
  '/qc': typeof QcRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/unleashed-sync': typeof UnleashedSyncRoute
  '/api/public/hooks/sync-fill-ready': typeof ApiPublicHooksSyncFillReadyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/customer-specs'
    | '/jobs'
    | '/line-setup'
    | '/live'
    | '/manufacturing'
    | '/qc'
    | '/settings'
    | '/stock'
    | '/unleashed-sync'
    | '/api/public/hooks/sync-fill-ready'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/calendar'
    | '/customer-specs'
    | '/jobs'
    | '/line-setup'
    | '/live'
    | '/manufacturing'
    | '/qc'
    | '/settings'
    | '/stock'
    | '/unleashed-sync'
    | '/api/public/hooks/sync-fill-ready'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/calendar'
    | '/customer-specs'
    | '/jobs'
    | '/line-setup'
    | '/live'
    | '/manufacturing'
    | '/qc'
    | '/settings'
    | '/stock'
    | '/unleashed-sync'
    | '/api/public/hooks/sync-fill-ready'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CalendarRoute: typeof CalendarRoute
  CustomerSpecsRoute: typeof CustomerSpecsRoute
  JobsRoute: typeof JobsRoute
  LineSetupRoute: typeof LineSetupRoute
  LiveRoute: typeof LiveRoute
  ManufacturingRoute: typeof ManufacturingRoute
  QcRoute: typeof QcRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  UnleashedSyncRoute: typeof UnleashedSyncRoute
  ApiPublicHooksSyncFillReadyRoute: typeof ApiPublicHooksSyncFillReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unleashed-sync': {
      id: '/unleashed-sync'
      path: '/unleashed-sync'
      fullPath: '/unleashed-sync'
      preLoaderRoute: typeof UnleashedSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qc': {
      id: '/qc'
      path: '/qc'
      fullPath: '/qc'
      preLoaderRoute: typeof QcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-setup': {
      id: '/line-setup'
      path: '/line-setup'
      fullPath: '/line-setup'
      preLoaderRoute: typeof LineSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-specs': {
      id: '/customer-specs'
      path: '/customer-specs'
      fullPath: '/customer-specs'
      preLoaderRoute: typeof CustomerSpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-fill-ready': {
      id: '/api/public/hooks/sync-fill-ready'
      path: '/api/public/hooks/sync-fill-ready'
      fullPath: '/api/public/hooks/sync-fill-ready'
      preLoaderRoute: typeof ApiPublicHooksSyncFillReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CalendarRoute: CalendarRoute,
  CustomerSpecsRoute: CustomerSpecsRoute,
  JobsRoute: JobsRoute,
  LineSetupRoute: LineSetupRoute,
  LiveRoute: LiveRoute,
  ManufacturingRoute: ManufacturingRoute,
  QcRoute: QcRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  UnleashedSyncRoute: UnleashedSyncRoute,
  ApiPublicHooksSyncFillReadyRoute: ApiPublicHooksSyncFillReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
